@startuml Схема работы банкомата
skinparam sequenceArrowThickness 0.5
left to right direction

actor Клиент
actor Банк

rectangle Банкомат {
Клиент -- (Снатие наличных)
Клиент -- (Проверка баланса)
Клиент -- (Получение кредита)
 (Снатие наличных) .> (Проверка баланса) : Автоматическая
Банк -- (Проверка работоспособности)
}

@enduml