@startuml
skinparam actorStyle awesome
skinparam packageStyle rectangle
actor Читатель
actor Библиотекарь

Библиотекарь -> ИнфСистема: Добавление книги
activate ИнфСистема
Библиотекарь -> ИнфСистема: Списание книги
deactivate ИнфСистема

group Регистрация
Читатель-> ИнфСистема: Запрос на регистрацию
activate ИнфСистема
ИнфСистема -> Читатель: Регистрация пользователя
deactivate ИнфСистема
end

group Выбор книги
Читатель-> ИнфСистема: Поиск книги
activate ИнфСистема
ИнфСистема -> Читатель: Результат поиска
Читатель-> ИнфСистема: Выбор книги
deactivate Читатель
deactivate ИнфСистема
end

group Получение книги
Читатель-> Библиотекарь: Запрос на выдачу выбранной книги
activate Библиотекарь
Библиотекарь -> Читатель: Выдача книги
Читатель -> Библиотекарь: Прием книги
Библиотекарь -> ИнфСистема: Изменение информации о читателе
activate ИнфСистема
Библиотекарь -> ИнфСистема: Списание книги
deactivate ИнфСистема
deactivate Библиотекарь
end

group Возврат книги
Читатель-> Библиотекарь: Возврат книги
activate Библиотекарь
Библиотекарь -> Читатель: Прием возврата книги
Библиотекарь -> ИнфСистема: Изменение информации о читателе
activate ИнфСистема
Библиотекарь -> ИнфСистема: Добавление книги
deactivate ИнфСистема
deactivate Библиотекарь
end

@enduml