@startuml "Диаграмма развертывания для Информационной системы библиотеки"
left to right direction


    

node Сервер {

    node БД{
        component СУБД {
            interface Интерфейс_СУБД
        }
        database БазаДанных
    }
    
    
    node ИнфСистема {
        component КаталогБД {
            interface ИнтерфейсКаталогаБД
        }
        component МодульБиблиотекаря {
            interface ИнтерфейсМодуляБиблиотекаря
        }
        component МодульЧитателя {
            interface ИнтерфейсМодуляЧитателя
        }
        
        ИнтерфейсКаталогаБД <--> Интерфейс_СУБД
        ИнтерфейсМодуляБиблиотекаря <--> Интерфейс_СУБД
        ИнтерфейсМодуляЧитателя <--> Интерфейс_СУБД
    }
}

node Клиент {
    artifact Браузер
}

Клиент <--> ИнтерфейсКаталогаБД : запрос на выдачу книги
Клиент <--> ИнтерфейсМодуляБиблиотекаря : запрос на \nдобавление/удаление\n книги в каталог
Клиент <--> ИнтерфейсМодуляЧитателя : запрос на добавление/изменение читателя


@enduml