@startuml "Сценарий"
left to right direction
skinparam actorStyle awesome
skinparam packageStyle rectangle
actor Читатель
actor Библиотекарь
actor Инф.Система


rectangle БИБЛИОТЕКА{

  
  Библиотекарь -- (Добавление книги)
  Библиотекарь -- (Удаление книги)
  
  Инф.Система -- (Регистрация читателя)
  Инф.Система -- (Изменение информации\n о читателе)
  
  Библиотекарь -- (Выдача книги)
  Библиотекарь -- (Прием книги)
   

  Читатель-- (Поиск книги)
  Читатель-- (Получение книги)
  Читатель-- (Возврат книги)

  
  
  (Выдача книги) .> (Изменение информации\n о читателе) : <<include>>
  (Прием книги) .> (Изменение информации\n о читателе) : <<include>>
  

}
@enduml
