@startuml "Сценарий"
actor Читатель
actor Библиотекарь

usecase "Добавление книги" as UC1
usecase "Удаление книги" as UC2
usecase "Регистрация читателя" as UC3
usecase "Изменение информации о читателе" as UC4
usecase "Выдача книги" as UC5
usecase "Прием книги" as UC6



Читатель --> UC6
Библиотекарь --> UC1
Библиотекарь --> UC2
Библиотекарь --> UC3
Библиотекарь --> UC4
Библиотекарь --> UC5



UC3 <-- Читатель
UC4 <-- Читатель
UC5 <-- Читатель
UC6 <-- Библиотекарь
@enduml