@startuml "Диаграмма классов для Информационной системы библиотеки"
class Книга{
    +Название :string
    +Автор: string
    +ГодИздания: datetime
    +ISBN: string
    +КоличествоЭкземпляров: integer
    +ПолучитьЭкземпляр()
    +ДобавитьЭкземпляр()
    +СписатьЭкземпляр()
}

class Читатель{
    +Имя: string
    +Фамилия: string
    +Адрес: string
    +НомерТелефона: integer
    +ИнформацияОВыдаче[]
    +ВзятьКнигу()
    +ВернутьКнигу()
    +ИсторияВыдачи()
}

class Библиотекарь{
    +Имя: string
    +Фамилия: string
    +Полное имя: string
    +НомерТелефона: integer
    +ВыдатьКнигу()
    +ПринятьКнигу()
    +ДобавитьКнигу()
    +УдалитьКнигу()
}

class ИнформационнаяСистема{
    +Каталог: Книга[]
    +Читатели: Читатель[]
    +Библиотекари: Библиотекарь[]
    +ДобавитьКнигу()
    +УдалитьКнигу()
    +ЗарегистрироватьЧитателя()
    +ИзменитьИнформациюОЧитателе()
    +ВыдатьКнигу()
    +ПринятьКнигу()
}

Читатель -- ИнформационнаяСистема : зарегистрирован
Книга -- ИнформационнаяСистема : вводится в каталог
Библиотекарь -- ИнформационнаяСистема : имеет доступ
Читатель -- Книга : может взять и вернуть
Библиотекарь -- Книга : может выдать и принять
@enduml