@startuml "iterator_visitor"
title Iterator && Visitor

class BurgerIterator {
    +__init__(self)
    + def print_burger(self)
    -include_cucumber(self, cucumber=False)
    -include_cheese(self, cheese=False)
    - include_tomato(self, tomato=False)
    - include_salad(self, salad=False)
    - include_bacon(self, bacon=False)
}



class CheeseBurger {
    +__init__(self)
    + print_burger(self)
    - include_additional(self)
}

class HealthyBurger {
    + print_burger(self)
    - __init__(self)
    - include_bacon(self, bacon=False)
    - include_cheese(self, cheese=False)
}


BurgerIterator <|-- CheeseBurger
BurgerIterator <|-- HealthyBurger

hide empty fields
@enduml